name: Trakt.tv Stats Generator

# Configure the workflow to run on a schedule (e.g., every day at 12:00 AM UTC)
on:
  schedule:
    - cron: '0 */5 * * *'
  # Allow manual triggering of the workflow from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  generate-stats-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to the github-actions bot
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python stats_generator.py
        env:
          TRAKT_API_KEY: ${{ secrets.TRAKT_API_KEY }}
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_APIKEY }}
          LASTFM_LIMIT: ${{ secrets.LASTFM_LIMIT }}
      # Step 5: Configure git and commit the changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/stats.json
          git commit -m "chore: Update stats" || echo "No changes to commit."
          git push origin main
